before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: kB/Y6PTsyEbeaufSnIFG2wkwCbRB2FWyOa2FEALK3t9Co/VBm2UxX64JwnQW3PzPlNHncv8kuRXD3k67TmAMxUGicxfGvEHLotfGMC7r5SIpFt3zobuD8AADkrF0WryMfSS7tEksN93O1dFJ7j0s/ZCwmm4ZEhtOTJsc9qsuplbXr4iLH44SgQ+UoG7h3L6P1bnPCaRwvPccQLbPVwqvuQus/6J7pRR0p+fckPS26aejXFeeWZuGD/EQMJljf6v9iMsKlhp5fwi77Nq5NKkAGZE4+1aMiVODZxaX9rqIWUzw0T6cUPGbKyLnxv/o2wD4JFP4Ibwj0S0+4gPiGBzp/q1xqWm0z2JG++pK4PWb1K9d2zRnECd6Fi+gckPtWX35jNju+YHQiBXKdsm4B/9RSgafAUQXmpvJxNJGQ1OBfRMfArcSXdqse0AM4XHQEbG3lEzxZRAC0KyNI8X2cnLCHY07xuZN/gcALqNNw0RXakMBv6CLPG1/k/Z90FwqS/DEdEwcchHDnPu3DEEjJjxl+f8QjmdQ2bKvpyEMu1jCYAGd92e//Y6PPmoV9W+xGqCa86tHm4Vn5ftHUBM85LNpBlS/DsAzmEVxl5rZGAzJOqzsTenVGhCBBHKgvVoazpCJ+03iZd108RCpRSusUU9qhR+NN/FMVV5/xj+qm2yqxjY= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
